#pragma checksum "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "f59ca4c72dd930f53290a70c6547a8d589cc2684"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\_ViewImports.cshtml"
using httpdeveloper.marvel.comdocsAPIMVCnewestversion;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\_ViewImports.cshtml"
using httpdeveloper.marvel.comdocsAPIMVCnewestversion.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
using RestSharp;

#line default
#line hidden
#nullable disable
#nullable restore
#line 11 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
using Marvel.Api;

#line default
#line hidden
#nullable disable
#nullable restore
#line 13 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
using Marvel.Api.Filters;

#line default
#line hidden
#nullable disable
#nullable restore
#line 14 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
using Marvel.Api.Model.DomainObjects;

#line default
#line hidden
#nullable disable
#nullable restore
#line 15 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
using Marvel.Api.Results;

#line default
#line hidden
#nullable disable
#nullable restore
#line 16 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
using Marvel.Api.Model;

#line default
#line hidden
#nullable disable
#nullable restore
#line 18 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
using Marvel;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"f59ca4c72dd930f53290a70c6547a8d589cc2684", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"9fc7b8971fe6ca07300fc50cdfc24bf9132e76e6", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/Styles/prism.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/Styles/main.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("src", new global::Microsoft.AspNetCore.Html.HtmlString("~/Scripts/prism.js"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Marvel API C# Wrapper";
    ViewBag.marvelDeveloper = "developer.marvel.com";
    Layout = null;

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n");
            WriteLiteral("\r\n");
            WriteLiteral("\r\n");
            WriteLiteral("\r\n");
            WriteLiteral("\r\n");
#nullable restore
#line 20 "C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\Views\Home\Index.cshtml"
  
    /*List<RestRequest> requestList =*/ /*(List<CharactersInResultViewModel>)*//*ViewBag.Message;*/

    /*List<RestResponse> responseList =*/ /*(List<RestResponse>)*//*ViewBag.Message;*/

    /*RestResponse restResponse =*/ /*(List<RestResponse>)*/

    //var items = new List<CharactersInResultViewModel>();

    //var items = ViewBag.Message;





    //items = ViewBag.Message;


#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<html>\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("head", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "f59ca4c72dd930f53290a70c6547a8d589cc26848045", async() => {
                WriteLiteral("\r\n    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "f59ca4c72dd930f53290a70c6547a8d589cc26848307", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
    <link rel=""stylesheet"" href=""//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"">
    <link rel=""stylesheet"" href=""https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css"">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700' rel='stylesheet' type='text/css'>
    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "f59ca4c72dd930f53290a70c6547a8d589cc26849860", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n    <meta name=\"viewport\" content=\"width=device-width\" />\r\n    <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("script", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "f59ca4c72dd930f53290a70c6547a8d589cc268411205", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js\"></script>\r\n    <script src=\"/Scripts/Index.js\"></script>\r\n");
                WriteLiteral("\r\n    <meta charset=\"utf-8\">\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n    <title></title>\r\n    <meta name=\"description\"");
                BeginWriteAttribute("content", " content=\"", 1996, "\"", 2006, 0);
                EndWriteAttribute();
                WriteLiteral(@">
    <meta name=""viewport"" content=""width=device-width"">
    <script type=""text/javascript"" src=""http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js""></script>
    <script src=""C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\handlebars-v4.7.7.js""></script>
");
                WriteLiteral("    <link rel=\"stylesheet\" href=\"style.css\">\r\n\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.HeadTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_HeadTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("body", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "f59ca4c72dd930f53290a70c6547a8d589cc268413978", async() => {
                WriteLiteral(@"

    <script src=""C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\handlebars-v4.7.7.js""></script>


    <div id=""results""></div>
    <div id=""status""></div>

    <script id=""reportTemplate"" type=""text/x-handlebars-template"">
        <script src=""C:\Users\Attila\source\repos\httpdeveloper.marvel.comdocsAPIMVCnewestversion\httpdeveloper.marvel.comdocsAPIMVCnewestversion\handlebars-v4.7.7.js""></script>

        <h1>{{year}}</h1>
        <p>
            Average Price: ${{avgPrice}}<br />
            Low/High Price: ${{minPrice}} / ${{maxPrice}}<br />
            Average Page Count: {{avgPageCount}}<br />
        </p>
        {{#each thumbs}}
        <img src=""{{this}}"" class=""thumb"">
        {{/each}}
        <br clear=""left"">
        <p />


    </script>
    <script ");
                WriteLiteral("></script>\r\n");
                WriteLiteral(@"    <script>

        /*try {*/



        /* global $,console,document,Handlebars */
        alert(""first alert"");
        //default not avail image
        var IMAGE_NOT_AVAIL = ""http://i.annihil.us/u/prod/marvel/i/mg/b/40/image_not_available"";

        alert(IMAGE_NOT_AVAIL);

        //my key
        var KEY = ""1f8c669bfb6d6b86aa65400c8f3ad03d"";

        alert(KEY);

        //credit: http://stackoverflow.com/a/1527820/52160



        /*window.onload =*/
        /*$(document).ready(function () {*/

        //getComicData();

        //getRandomInt();

        alert(""Test if alert works"");


        var $results = $(""#results"");
        var $status = $(""#status"");

        var templateSource = $(""#reportTemplate"").html();
        //var template = Handlebars.compile(templateSource);
        //alert(template);
        var start = 2013;
        var end = 1950;

        //alert(""Test if alert works"");

        var promises = [];

        alert(start.toString());
");
                WriteLiteral(@"
        /*alert(end);*/

        $status.html(""<i>Getting comic book data - this will be slow - stand by...</i>"");


        alert($status.html);

        alert($status.html.toString());

        alert(status);

        alert(status.toString());

        for (var x = start; x >= end; x--) {
            promises.push(getComicData(x));
            alert(promises);
            alert(promises.toString());
        }

        $.when.apply($, promises).done(function () {

            var args = Array.prototype.slice.call(arguments, 0);

            alert(args);

            alert(args.toString());


            $status.html("""");

            for (var x = 0; x < args.length; x++) {
                var year = start - x;
                console.log(""displaying year"", year);

                var stats = {};
                stats.year = year;
                stats.priceTotal = 0;
                stats.priceCount = 0;
                stats.minPrice = 999999999;
                stats");
                WriteLiteral(@".maxPrice = -999999999;
                stats.pageTotal = 0;
                stats.pageCount = 0;
                stats.pics = [];

                alert(stats);

                var res = args[x][0];

                alert(res);

                if (res.code === 200) {
                    for (var i = 0; i < res.data.results.length; i++) {
                        var comic = res.data.results[i];
                        //just get the first item
                        if (comic.prices.length && comic.prices[0].price !== 0) {
                            stats.priceTotal += comic.prices[0].price;
                            if (comic.prices[0].price > stats.maxPrice) stats.maxPrice = comic.prices[0].price;
                            if (comic.prices[0].price < stats.minPrice) stats.minPrice = comic.prices[0].price;
                            stats.priceCount++;
                        }
                        if (comic.pageCount > 0) {
                            stats.pageTotal += com");
                WriteLiteral(@"ic.pageCount;
                            stats.pageCount++;
                        }
                        if (comic.thumbnail && comic.thumbnail.path != IMAGE_NOT_AVAIL) stats.pics.push(comic.thumbnail.path + ""."" + comic.thumbnail.extension);

                    }
                    stats.avgPrice = (stats.priceTotal / stats.priceCount).toFixed(2);
                    stats.avgPageCount = (stats.pageTotal / stats.pageCount).toFixed(2);

                    //pick 5 thumbnails at random
                    stats.thumbs = [];
                    while (stats.pics.length > 0 && stats.thumbs.length < 5) {
                        var chosen = getRandomInt(0, stats.pics.length);
                        stats.thumbs.push(stats.pics[chosen]);
                        stats.pics.splice(chosen, 1);
                    }

                    console.dir(stats);
                    var html = template(stats);
                    $results.append(html);
                    alert(html);
          ");
                WriteLiteral(@"      }
            }
        });


        function getRandomInt(min, max) {
            return Math.floor(Math.random() * (max - min + 1)) + min;
            alert(max);
        }

        function getComicData(year) {
            var url = ""http://gateway.marvel.com/v1/public/comics?limit=100&format=comic&formatType=comic&dateRange="" + year + ""-01-01%2C"" + year + ""-12-31&apikey="" + KEY;
            console.log('getComicData(' + year + ')');
            alert(year);
            return $.get(url);
            alert(url);
        }

        /* });*/



        //}

        //catch (e) {
        //    alert(e);
        //}





        //alert(getMarvelResponse.data);
        //alert('ok');

        //alert(getMarvelResponse);

        var PRIV_KEY = ""b7e37b0815b570c2f84f0267060b0637698ed06a"";
        var PUBLIC_KEY = ""1f8c669bfb6d6b86aa65400c8f3ad03d"";

        //alert(PUBLIC_KEY);


        //        Request Url: http://gateway.marvel.com/v1/public/comics
        /");
                WriteLiteral(@"/        Request Method: GET
        //        Params: {
        //            ""apikey"": ""your api key"",
        //                ""ts"": ""a timestamp"",
        //                    ""hash"": ""your hash""
        //        }
        //        Headers: {
        //            Accept: *
        //}

        const http = new XMLHttpRequest()

        http.open(""GET"", ""http://gateway.marvel.com/v1/public/comics"", true, ""1f8c669bfb6d6b86aa65400c8f3ad03d"")
        http.send()

        http.onload = () => console.log(http.responseText)

            //alert(http.responseText);




                                    //try {

                                    //    $(function myFunction () {
                                    //        var marvelAPI = 'https://gateway.marvel.com/v1/public/comics';
                                    //        try {
                                    //        $.getJSON(marvelAPI, {
                                    //            apikey: '1f8c669bfb6d6b86");
                WriteLiteral(@"aa65400c8f3ad03d',
                                    //            alert($);
                                    //        })

                                    //            .done(function (response) {
                                    //alert($);
                                    //                alert(response);
                                    //                alert(response.data.results);
                                    //                var results = response.data.results;
                                    //                alert(results);
                                    //                var resultsLen = results.length;
                                    //                alert(results.length);
                                    //                var output = '<ul>';

                                    //                alert(""right"");

                                    //                for (var i = 0; i < resultsLen; i++) {
                                ");
                WriteLiteral(@"    //                    if (results[i].images.length > 0) {
                                    //                        var imgPath = results[i].images[0].path + '/standard_xlarge.' + results[i].images[0].extension;
                                    //                        output += '<li><img src=""' + imgPath + '""><br>' + results[i].title + '</li>';
                                    //                    }
                                    //                }
                                    //                output += '</ul>'
                                    //                $('#results').append(output);
                                    //            });
                                    //        }
                                    //        catch (err) {
                                    //            /*alert(""error"");
                                    //            alert(err.message);
                                    //            document.getElementById(""demo""");
                WriteLiteral(@").innerHTML = err.message;
                                    //        }

                                    //    });

                                    //}

                                    //catch (err) {
                                    //    alert(""error"");
                                    //    alert(err.message);
                                    //    document.getElementById(""demo"").innerHTML = err.message;
                                    //}












                                        //function getMarvelResponse() {

                                        //    // you need a new ts every request
                                        //    var ts = new Date().getTime();
                                        //    var hash = CryptoJS.MD5(ts + PRIV_KEY + PUBLIC_KEY).toString();

                                        //    // the api deals a lot in ids rather than just the strings you want to use
                                        //");
                WriteLiteral(@"    var characterId = '1009351'; // hulk


                                        //    var url = 'http://gateway.marvel.com:80/v1/public/comics';

                                        //    console.log(url);
                                        //    alert(url.toString);

                                        //    $.getJSON(url, {
                                        //        ts: ts,
                                        //        apikey: ""1f8c669bfb6d6b86aa65400c8f3ad03d"",
                                        //        hash: hash,
                                        //        characters: ""1009351""
                                        //    })
                                        //        .done(function (data) {
                                        //            // sort of a long dump you will need to sort through
                                        //            console.log(data);
                                        //            alert(data.toString)");
                WriteLiteral(@";
                                        //        })
                                        //        .fail(function (err) {
                                        //            // the error codes are listed on the dev site
                                        //            console.log(err);
                                        //            alert(err.toString);
                                        //        });
                                        //    alert(getMarvelResponse.data.toString);
                                        //};

                                        //getMarvelResponse();
                                        //window.onload = getMarvelResponse();

                                        //alert(getMarvelResponse.data.toString);

    </script>

    <div id=""status""></div>

    <div id=""reportTemplate""></div>


    <div id=""results""></div>

    <p id=""demo""></p>

    <h1>Marvel API</h1>
");
                WriteLiteral("\r\n    <table class=\"col s12\">\r\n");
                WriteLiteral("\r\n\r\n");
                WriteLiteral("\r\n\r\n\r\n");
                WriteLiteral("\r\n\r\n\r\n");
                WriteLiteral("\r\n\r\n");
                WriteLiteral("\r\n");
                WriteLiteral("        <tr>\r\n\r\n\r\n");
                WriteLiteral("\r\n");
                WriteLiteral("\r\n\r\n");
                WriteLiteral("\r\n");
                WriteLiteral("\r\n\r\n");
                WriteLiteral("\r\n\r\n\r\n");
                WriteLiteral("\r\n\r\n\r\n");
                WriteLiteral("\r\n        </tr>\r\n");
                WriteLiteral("    </table>\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.BodyTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_BodyTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n</html>\r\n");
            WriteLiteral("\r\n");
            WriteLiteral("<!-- Modal Structure -->\r\n");
            WriteLiteral("    ");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
